### ISSUE TITLE
Best Practices for Amazon SQS

### ISSUE THREAD

**Issue by hkdnet** [hkdnet/readings#1]
https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/sqs-best-practices.html

- Recommendations for Standard and FIFO Queues
  - Working with Messages
  - Reducing Costs
  - Moving from a Standard Queue to a FIFO Queue
- Additional Recommendations for FIFO Queues
  - Using the Message Deduplication ID
  - Using the Message Group ID
  - Using the Receive Request Attempt ID

**Comment by hkdnet** [comment]
# Recommendations for Standard and FIFO Queues

## working with messages

visibility timeoutをちゃんと設定せよ

waitは20secを推奨(理由は知らない)
20秒以内にメッセージがついたらはやくかえってくることを確認する

キュー1個に1スレッド使う

デッドレターキューを使う
デッドレターキューにはいったあとの生存期間は元のメッセージから数えることに注意。
元が 1/1 12:00 開始 → 24hours でデッドレターキュー、dlqが3days の場合のこりは 48hours

デッドレターキューの受信件数を1にしてはいけない、かな？英語に自信がない

RPC の間に SQS を挟むケースがあるっぽい。その場合は返信のキューを都度作成するのではなく、 attr として表現するべき。

## Reducing Costs

バッチ処理しろ
ロングポーリングしろ

## Moving from a Standard Queue to a FIFO Queue

( 中身なかった )

**Comment by hkdnet** [comment]
# Additional Recommendations for FIFO Queues
## Using the Message Deduplication ID

dedupすると5分間は同じdedup idのメッセージを受け付けないよ（最初のが残る点に注意）
dedupはgroupではなくキュー全体で効くよ
なんと、メッセージがデリートされた後にも効くよ！

memo: すなわち dedup はほんとに **同じ** メッセージであるときに指定すればよさそうだ。メッセージの必要な属性から hash 生成して指定するのがよさそう。

なお dedup を使用する場合にもコンシューマ・プロデューサはNW不通とかに気をつけること。
min dedupは5minなので、それを超えるとメッセージの再送が起きる。

## Using the Message Group ID

message group idは一つずつシリアルに処理されるようにするやつ
順序よりも速度重視ならグループIDはかぶせないようにする

## Using the Receive Request Attempt ID

死んだ時の再送用にReceiveRequestAttemptIDを用いよ

**Comment by hkdnet** [comment]
# TODO

- [ ] デッドレターキューに入ったやつのアラートどうする？ CloudWatch とかでなにかある？
- [ ] To avoid inconsistent message processing by standard queues, avoid setting the number of maximum receives to 1 when you configure a dead-letter queue. In some unlikely scenarios, if you set the number of maximum receives to 1, any time a ReceiveMessage call fails, a message might be moved to a dead-letter queue without being received.
- [ ] Reducing Costs のためには一回で 1 メッセージをとるような縛りはやめたほうがよい？実装コストおもそうなので要検討( go とはいえ勝手に goroutine がいきなり生えたら困るだろう)
